-- SESSION #01
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- SESSION #02
 BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
 
-- SESSION #01
 SELECT SUM(rating) FROM pizzeria;
 
-- SESSION #02
INSERT INTO pizzeria (id, name, rating) VALUES (11, 'Kazan Pizza 2', 4);
 COMMIT;
 
-- SESSION #01
SELECT SUM(rating) FROM pizzeria;
COMMIT;
SELECT SUM(rating) FROM pizzeria;

-- SESSION #02
SELECT SUM(rating) FROM pizzeria;